export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/"
export const REGISTRATION_ROUTE = "/registration"
export const SHOP_ROUTE = "/home"
export const BASKET_ROUTE = "/basket"
export const GOODS_ROUTE = "/goods"